### ISSUE TITLE
Implement euclidean division for integers

### ISSUE THREAD

**Issue by dr-orlovsky** [internet2-org/rust-aluvm#10]
Related: https://github.com/LNP-BP/rust-amplify/issues/90

https://github.com/internet2-org/rust-aluvm/blob/14c48e90e8972543962d51b52bb8900c173548aa/src/reg/arithm.rs#L206-L208

**Comment by 6293** [comment]
@dr-orlovsky Although most of the time integer division will not overflow, MAX / -1 does (e.g. -128i8 / -1i8 = 128), so we may want to wrap the result in `int_div` too. Are we still going to overload `wrap` flag as Euclid div flag?

**Comment by dr-orlovsky** [comment]
I think on division overflow we need to set `st0` to false and that's all - as for any other arithmetic overflows. So probably we still can uses `wrap` flag for Euclid division. What do you think?

**Comment by 6293** [comment]
agree
