### ISSUE TITLE
When `Number`s are less than 128, `to_u1024_bytes` converts them to zero

### ISSUE THREAD

**Issue by z8674558** [internet2-org/rust-aluvm#30]
@dr-orlovsky 

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ops_on_numbers() {
        let num1 = Number::from(127);
        assert_eq!(false, num1.is_zero())
    }
}
```

results in:
```
thread 'data::arithm::tests::ops_on_numbers' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src/data/arithm.rs:513:9
```

because of this:
https://github.com/internet2-org/rust-aluvm/blob/3b16ef83bad1b02137261739f9d22dfc1a966d6f/src/data/number.rs#L1066

It seems that 0 will be assigned to `len` when the number of bits is below 7, while 1 should be assigned.

**Comment by dr-orlovsky** [comment]
This us a very good catch! Will work on fix
