### ISSUE TITLE
fix `neg` for `Number`

### ISSUE THREAD

**Issue by z8674558** [internet2-org/rust-aluvm#33]
```rust
#[test]
    fn test_neg() {
        let x = Number::from(1i8);
        let y = Number::from(-1i8);
        assert_eq!(x.neg(), y);
    }
```

fails with

```
left: `Number { layout: Integer(IntLayout { signed: true, bytes: 1 }), bytes: "81" }`,
right: `Number { layout: Integer(IntLayout { signed: true, bytes: 1 }), bytes: "ff" }`'
```

Also, when the Number is unsigned, we could:
- panic
- accordingly change the `IntLayout` to signed (if it would cause overflow, change the `bytes` in the layout too)
- accordingly change the `IntLayout` to signed (if it caused overflow, panic)

@dr-orlovsky wdyt? have a happy new year

**Comment by dr-orlovsky** [comment]
Hm, in rust `assert_eq!(1u8, -1i8.neg())` will just fail to compile. I assume we need to change signed layout into an unsigned for such a comparison - this conversion will not fail.

**Comment by dr-orlovsky** [comment]
And have a happy New Year too!

**Comment by z8674558** [comment]
Excuse my misleading sentences above, I was talking about how we deal with

```rust
let x = Number::from(255u8);
x.neg()
```
this Number has `{ layout: Integer(IntLayout { signed: false, bytes: 1 }), bytes: "ff" }`. To get `Number` representing -255, we need 2 bytes, so we need to either prohibit `neg` method for unsigned int, or return `Number` with extended bytes.

**Comment by z8674558** [comment]
As for the bug, we need to invert all the digits then add 1 here:

https://github.com/internet2-org/rust-aluvm/blob/d67e2f558cf7c300dbd516897e81e5b13a82b609/src/data/number.rs#L812

**Comment by dr-orlovsky** [comment]
This is a tricky question, we have a lot of tradeoffs here... I will try think loudly.

`Number` type is not just a number itself, it serves AluVM purposes. And AluVM should not fail/panic on any exceptions; instead, if the operation is impossible, the destination register must be set into `None` state and `st0` set to `false`. Thus, I think we need to change method signature such that it will return `Result` – and in the call sites this `Result` should be handled for error cases doing this to the destination and `st0` registers.

**Comment by z8674558** [comment]
Thank you for the insight, I have a better understanding now. I fixed my code to let the instruction handle the result of `neg` method (applying_sign, without_sign, neg, abs now returns `Option<Number>`)
